tickers = {
            "NSE": [
                "ADANIENT",
                "ADANIPORTS",
                "APOLLOHOSP",
                "ASIANPAINT",
                "AXISBANK",
                "BAJAJ-AUTO",
                "BAJAJFINSV",
                "BAJFINANCE",
                "BHARTIARTL",
                "BPCL",
                "BRITANNIA",
                "CIPLA",
                "COALINDIA",
                "DIVISLAB",
                "DRREDDY",
                "EICHERMOT",
                "GRASIM",
                "HCLTECH",
                "HDFCBANK",
                "HDFCLIFE",
                "HEROMOTOCO",
                "HINDALCO",
                "HINDUNILVR",
                "ICICIBANK",
                "INDUSINDBK",
                "INFY",
                "ITC",
                "JSWSTEEL",
                "KOTAKBANK",
                "LT",
                "LTIM",
                "M&M",
                "MARUTI",
                "NESTLEIND",
                "NTPC",
                "ONGC",
                "POWERGRID",
                "RELIANCE",
                "SBILIFE",
                "SBIN",
                "SHRIRAMFIN",
                "SUNPHARMA",
                "TATACONSUM",
                "TATAMOTORS",
                "TATASTEEL",
                "TCS",
                "TECHM",
                "TITAN",
                "ULTRACEMCO",
                "WIPRO"
            ],
            "BSE": [
                "500002",
                "539254",
                "512599",
                "541450",
                "532921",
                "533096",
                "500425",
                "500820",
                "540376",
                "532215",
                "532977",
                "500034",
                "532978",
                "500490",
                "532134",
                "500049",
                "500547",
                "532454",
                "500825",
                "500093",
                "511243",
                "500087",
                "533278",
                "500830",
                "500480",
                "500096",
                "532488",
                "532868",
                "500124",
                "505200",
                "532155",
                "532424",
                "500300",
                "517354",
                "532281",
                "500180",
                "540777",
                "500182",
                "500440",
                "541154",
                "500696",
                "500188",
                "532174",
                "540716",
                "540133",
                "530965",
                "532388",
                "543257",
                "534816",
                "532187",
                "500209",
                "539448",
                "500875",
                "543940",
                "533148",
                "500228",
                "500247",
                "500510",
                "543526",
                "540005",
                "500257",
                "543287",
                "500520",
                "532500",
                "500790",
                "532555",
                "500312",
                "533106",
                "500331",
                "542652",
                "532810",
                "532898",
                "532461",
                "542649",
                "532955",
                "500325",
                "517334",
                "540719",
                "511218",
                "500550",
                "500112",
                "524715",
                "532667",
                "532540",
                "500800",
                "500570",
                "500400",
                "500470",
                "532755",
                "500114",
                "500420",
                "500251",
                "532343",
                "532538",
                "532432",
                "540180",
                "500295",
                "507685",
                "543320",
                "532321"
            ],
            "BSE_NAMES": [
                "ABB India Limited",
                "Adani Energy Solutions Ltd",
                "ADANI ENTERPRISES LTD.",
                "Adani Green Energy Ltd",
                "ADANI PORTS AND SPECIAL ECONOMIC ZONE LTD.",
                "ADANI POWER LTD.",
                "AMBUJA CEMENTS LTD.",
                "ASIAN PAINTS LTD.",
                "Avenue Supermarts Ltd",
                "AXIS BANK LTD.",
                "BAJAJ AUTO LTD.",
                "Bajaj Finance Limited",
                "BAJAJ FINSERV LTD.",
                "BAJAJ HOLDINGS & INVESTMENT LTD.",
                "BANK OF BARODA",
                "BHARAT ELECTRONICS LTD.",
                "BHARAT PETROLEUM CORPORATION LTD.",
                "BHARTI AIRTEL LTD.",
                "BRITANNIA INDUSTRIES LTD.",
                "CG Power and Industrial Solutions Ltd",
                "Cholamandalam Investment and Finance Company Ltd",
                "CIPLA LTD.",
                "COAL INDIA LTD.",
                "COLGATE-PALMOLIVE (INDIA) LTD.",
                "CUMMINS INDIA LTD.",
                "DABUR INDIA LTD.",
                "DIVI'S LABORATORIES LTD.",
                "DLF LTD.",
                "DR.REDDY'S LABORATORIES LTD.",
                "EICHER MOTORS LTD.",
                "GAIL (INDIA) LTD.",
                "GODREJ CONSUMER PRODUCTS LTD.",
                "GRASIM INDUSTRIES LTD.",
                "HAVELLS INDIA LTD.",
                "HCL TECHNOLOGIES LTD.",
                "HDFC Bank Ltd",
                "HDFC Life Insurance Company Ltd",
                "HERO MOTOCORP LTD.",
                "HINDALCO INDUSTRIES LTD.",
                "Hindustan Aeronautics Ltd",
                "HINDUSTAN UNILEVER LTD.",
                "HINDUSTAN ZINC LTD.",
                "ICICI BANK LTD.",
                "ICICI Lombard General Insurance Company Ltd",
                "ICICI Prudential Life Insurance Company Ltd",
                "INDIAN OIL CORPORATION LTD.",
                "INDIAN OVERSEAS BANK",
                "Indian Railway Finance Corporation Ltd",
                "Indus Towers Ltd",
                "INDUSIND BANK LTD.",
                "INFOSYS LTD.",
                "InterGlobe Aviation Ltd",
                "ITC LTD.",
                "Jio Financial Services Ltd",
                "JSW Energy Ltd",
                "JSW STEEL LTD.",
                "KOTAK MAHINDRA BANK LTD.",
                "LARSEN & TOUBRO LTD.",
                "Life Insurance Corporation of India",
                "LTIMindtree Ltd",
                "LUPIN LTD.",
                "Macrotech Developers Ltd",
                "MAHINDRA & MAHINDRA LTD.",
                "MARUTI SUZUKI INDIA LTD.",
                "NESTLE INDIA LTD.",
                "NTPC LTD.",
                "Oil and Natural Gas Corporation Ltd",
                "OIL INDIA LTD.",
                "PIDILITE INDUSTRIES LTD.",
                "Polycab India Ltd",
                "POWER FINANCE CORPORATION LTD.",
                "POWER GRID CORPORATION OF INDIA LTD.",
                "PUNJAB NATIONAL BANK",
                "Rail Vikas Nigam Ltd",
                "REC Ltd",
                "RELIANCE INDUSTRIES LTD.",
                "Samvardhana Motherson International Ltd",
                "SBI Life Insurance Company Ltd",
                "Shriram Finance Ltd",
                "SIEMENS LTD.",
                "STATE BANK OF INDIA",
                "SUN PHARMACEUTICAL INDUSTRIES LTD.",
                "SUZLON ENERGY LTD.",
                "TATA CONSULTANCY SERVICES LTD.",
                "Tata Consumer Products Ltd",
                "TATA MOTORS LTD.",
                "TATA POWER CO.LTD.",
                "TATA STEEL LTD.",
                "TECH MAHINDRA LTD.",
                "Titan Company Limited",
                "TORRENT PHARMACEUTICALS LTD.",
                "TRENT LTD.",
                "TVS MOTOR COMPANY LTD.",
                "ULTRATECH CEMENT LTD.",
                "UNITED SPIRITS LTD.",
                "Varun Beverages Ltd",
                "Vedanta Limited",
                "WIPRO LTD.",
                "Zomato Ltd",
                "Zydus Lifesciences Ltd"
            ]
}
